services:
  postgres:
    image: "postgres"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=567234"
      - "POSTGRES_DB=hw02"
    ports:
      - "5432:5432"
  app:
    build: "."
    ports:
      - "8000:8000"
    depends_on:
      - "postgres"
